site_name: My Docs
theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon-32x32.webp
  logo: images/apple-touch-icon.png

  features:
    - navigation.expand
# Page tree
nav:
  - 'Home': 'SUMMARY.md'
  - '创之轨迹':
    - 'Overview': 'hajimari/summary.md'
    - '追忆石盘':
      - '退路、岔路、前方的路': 'hajimari/episodes/ep1.md'
plugins:
  - git-revision-date-localized
  - search:
      lang:
        - ja
        - en
      prebuild_index: true
