name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Init submodule
        run: |
          git submodule init
          git submodule update --remote
      - name: Install python dependencies
        run: |
          pip3 install mkdocs-material
          pip3 install -r requirements.txt
      - name: Build mkdocs and deploy
        run: mkdocs gh-deploy --force
